### PR TITLE
1. Fixed a bug where animation was automatically removed from layer w…

### PR DESCRIPTION
**Pull request by pegurov**
…hen it was not in the view hierarchy (for example when you were trying to show it in viewDidLoad)

2. Removed unused code

### CODE REVIEW

**Comment by icodesign** [comment]
Hey @pegurov , thanks for the PR. I'm not quite understand the bug. Could you give me some sample code?

**Comment by pegurov** [comment]
```
import UIKit

/*
 The bug is that if this controller is presented MODALLY and you want
 to show the indicator in viewDidLoad(), the indicator will show, but
 there will be no animation.
 */

class SecondController: UIViewController {

    var activityIndicator: ICDMaterialActivityIndicatorView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        showIndicator()
    }
    
    func showIndicator() {
        
        activityIndicator = ICDMaterialActivityIndicatorView()
        view.addSubview(activityIndicator)
        activityIndicator.startAnimating()
    }
}
```

**Comment by pegurov** [comment]
I suspect that this is due to the fact that before animating a modal presentation UIKit ends all current animations in the view and its layers. And so animation is removed immediately and you never see it again

**Comment by icodesign** [comment]
Awesome. Thank you!

**Comment by icodesign** [comment]
Cocoapods updated.

**Pull request merged**
